sudo: false
dist: trusty
language: php

notifications:
  on_success: never
  on_failure: change
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest WP_TRAVISCI=phpcs
    - php: 7.1
      env: WP_VERSION=latest WP_TRAVISCI=phpcs
    - php: 7.0
      env: WP_VERSION=latest WP_TRAVISCI=phpcs
    - php: 5.6
      env: WP_VERSION=4.4 WP_TRAVISCI=phpcs
    - php: 5.6
      env: WP_VERSION=latest WP_TRAVISCI=phpcs
    - php: 5.6
      env: WP_VERSION=trunk WP_TRAVISCI=phpcs
    - php: 5.6
      env: WP_TRAVISCI=phpcs WP_VERSION=latest
    - php: 5.3
      env: WP_VERSION=latest WP_TRAVISCI=phpcs
      dist: precise


env:
  - WP_PROJECT_TYPE=plugin $WP_VERSION WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

matrix:
  allow_failures:
    - php: nightly

before_script:
  - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  
  - echo "Running Code Sniffer. phpcs"
  - composer global require wp-coding-standards/wpcs
  - phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - phpcs -n
  #- phpcs --standard=WordPress .
  - phpcs -p -s -v -n --standard=WordPress .
  - phpcbf -n -p -v
  